Update PBAutoBuild250.yml

diff --git a/.github/workflows/PBAutoBuild250.yml b/.github/workflows/PBAutoBuild250.yml
--- a/.github/workflows/PBAutoBuild250.yml
+++ b/.github/workflows/PBAutoBuild250.yml
@@ -26,9 +26,9 @@ jobs:
         shell: cmd
         run: |  
           dir "C:\Program Files (x86)\Appeon\Common\PowerBuilder" 2>nul  || echo "Appeon folder not found."
+          dir "C:\Program Files (x86)\MSBuild" 2>nul  || echo "MSBuild folder not found." 
         
       - name: Set SYSTEMDRIVE (Not recommended)
-
         shell: cmd
         run: |  
           dir "C:\Program Files (x86)\Appeon\PowerBuilderUtilities 25.0" 2>nul  || echo "Appeon folder not found."
