Update PBAutoBuild250.yml

diff --git a/.github/workflows/PBAutoBuild250.yml b/.github/workflows/PBAutoBuild250.yml
--- a/.github/workflows/PBAutoBuild250.yml
+++ b/.github/workflows/PBAutoBuild250.yml
@@ -12,23 +12,22 @@ jobs:
     steps:
       - uses: actions/checkout@v3
                 
-      #- name: Install Runtime
-      #  shell: cmd  # Specify cmd shell
-      #  run: |
-      #    PowerBuilderRuntime.exe /s
-      #    exit 0
+      - name: Install Runtime
+        shell: cmd  # Specify cmd shell
+        run: |
+          PowerBuilderRuntime.exe /s
+          exit 0
           
-      #- name: Install Util
-      #  shell: cmd  # Specify cmd shell
-      #  run: |
-      #    PowerBuilderUtilities.exe /s
-      #    exit 0
+      - name: Install Util
+        shell: cmd  # Specify cmd shell
+        run: |
+          PowerBuilderUtilities.exe /s
+          exit 0
         
       - name: Set SYSTEMDRIVE (Not recommended)
         shell: cmd
         run: |  
-          dir "C:\Program Files (x86)\Appeon\Common\PowerBuilder" 2>nul  || echo "PowerBuilder folder not found."
-          dir "C:\Program Files (x86)"
+          dir "C:\Program Files (x86)\Appeon\Common\PowerBuilder" 2>nul  || echo "Appeon folder not found."
           dir "D:\a\repo-name\repo-name"
           
       - name: Set SYSTEMDRIVE (Not recommended)
